### ISSUE TITLE
output parameter

### ISSUE THREAD

**Issue by tosseto** [tbicr/osn2osm#2]
.osn file have timestamp of "created_at" and "closed_at", this tool cannot output these value. How can I get it?

**Comment by tbicr** [comment]
Hi, you can put it in tags, osm xml format doesn't have this data in tags: https://wiki.openstreetmap.org/wiki/OSM_XML

**Comment by tosseto** [comment]
Thank you for reply. Your suggest is correct.  Another possibility may be to pick up "closed_at" string from the name tag.
